server:
  port: 8002 # ???????

spring:
  application:
    name: customer-service # ?????nacos ???????
  cloud:
    nacos:
      discovery:
        username: nacos # nacos ?????
        password: nacos # nacos ??
        server-addr: 127.0.0.1:8848 # nacos ?????
